[tox]
envlist = py312,type,lint,doc
isolated_build = true

[testenv]
extras =
  dev
  query
commands = pytest --no-cov

[testenv:pytorch]
extras =
  dev
  query
  pytorch
  viewer
commands = pytest

[testenv:viewer]
extras =
  dev
  query
  viewer
setenv = QT_QPA_PLATFORM=offscreen
commands = pytest --no-cov

[testenv:type]
extras =
  dev
  query
  pytorch
  viewer
commands = mypy src examples

[testenv:lint]
extras = dev
commands =
  ruff check src tests docs benchmarks examples
  docformatter --check --recursive src tests benchmarks examples

[testenv:doc]
extras =
  dev
  docs
commands = sphinx-build -b html -W docs docs/_build/html
